title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman

conference_name: The 1st Workshop on Recommendation with Generative Models
conference_intro: "Will be held in 2023"

github:
  zip_url: http://www.google.com

collections:
  organizers:
    output: true
  speakers:
    output: true